export const MOCK_RACEDAY_PROPERTIES = {
  track: undefined,
  race: undefined,
  heat: undefined,
  totalHeats: 0,
  qrCodeUrl: "",
  formattedTime: "0:00.00",
  autoStatusLabel: "",
  isWarmup: false,
  showCountdownOverlay: false,
  raceRecordLapNickname: "RecordHolder",
  raceRecordLapTime: "5.000",
  raceRecordScoreNickname: "ScoreHolder",
  raceRecordScore: "10",
  currentRaceBestNickname: "RaceBest",
  currentRaceBestTime: "5.100",
  heatBestNickname: "HeatBest",
  heatBestTime: "5.200",
  leaderboardEntries: [] as any[],
};
