export interface TemplateVariable {
  expression: string;
  category:
    | "standings"
    | "heats"
    | "heatDriver"
    | "laps"
    | "driverSummaries"
    | "season"
    | "race";
  categoryKey: string;
  type: string;
  descriptionKey: string;
  example: string;
}

export const TEMPLATE_VARIABLES: TemplateVariable[] = [
  // 1. Overall Standings (items="standings" var="driver")
  {
    expression: "${driver.rank}",
    category: "standings",
    categoryKey: "UE_VAR_CAT_STANDINGS",
    type: "Number",
    descriptionKey: "UE_VAR_DESC_STANDINGS_POSITION",
    example: "1",
  },
  {
    expression: "${driver.driver.name}",
    category: "standings",
    categoryKey: "UE_VAR_CAT_STANDINGS",
    type: "String",
    descriptionKey: "UE_VAR_DESC_STANDINGS_DRIVER_NAME",
    example: '"Austin"',
  },
  {
    expression: "${driver.totalLaps}",
    category: "standings",
    categoryKey: "UE_VAR_CAT_STANDINGS",
    type: "Decimal",
    descriptionKey: "UE_VAR_DESC_STANDINGS_TOTAL_LAPS",
    example: "45.820",
  },
  {
    expression: "${driver.totalTime}",
    category: "standings",
    categoryKey: "UE_VAR_CAT_STANDINGS",
    type: "Seconds",
    descriptionKey: "UE_VAR_DESC_STANDINGS_TOTAL_TIME",
    example: "184.210",
  },
  {
    expression: "${driver.bestLapTime}",
    category: "standings",
    categoryKey: "UE_VAR_CAT_STANDINGS",
    type: "Seconds",
    descriptionKey: "UE_VAR_DESC_STANDINGS_FAST_LAP",
    example: "3.892",
  },
  {
    expression: "${driver.averageLapTime}",
    category: "standings",
    categoryKey: "UE_VAR_CAT_STANDINGS",
    type: "Seconds",
    descriptionKey: "UE_VAR_DESC_STANDINGS_AVG_LAP",
    example: "4.105",
  },
  {
    expression: "${driver.medianLapTime}",
    category: "standings",
    categoryKey: "UE_VAR_CAT_STANDINGS",
    type: "Seconds",
    descriptionKey: "UE_VAR_DESC_STANDINGS_MEDIAN_LAP",
    example: "4.088",
  },
  {
    expression: "${driver.gapLeader}",
    category: "standings",
    categoryKey: "UE_VAR_CAT_STANDINGS",
    type: "String",
    descriptionKey: "UE_VAR_DESC_STANDINGS_GAP_LEADER",
    example: '"+1.240"',
  },
  {
    expression: "${driver.gapPosition}",
    category: "standings",
    categoryKey: "UE_VAR_CAT_STANDINGS",
    type: "String",
    descriptionKey: "UE_VAR_DESC_STANDINGS_GAP_POSITION",
    example: '"+0.410"',
  },
  {
    expression: "${driver.laneLaps[0]}",
    category: "standings",
    categoryKey: "UE_VAR_CAT_STANDINGS",
    type: "Decimal",
    descriptionKey: "UE_VAR_DESC_STANDINGS_LANE_LAPS",
    example: "12.0",
  },
  {
    expression: "${driver.positionPoints}",
    category: "standings",
    categoryKey: "UE_VAR_CAT_STANDINGS",
    type: "Decimal",
    descriptionKey: "UE_VAR_DESC_STANDINGS_POS_POINTS",
    example: "25.0",
  },
  {
    expression: "${driver.overallBonusPoints}",
    category: "standings",
    categoryKey: "UE_VAR_CAT_STANDINGS",
    type: "Decimal",
    descriptionKey: "UE_VAR_DESC_STANDINGS_BONUS_POINTS",
    example: "1.0",
  },
  {
    expression: "${driver.heatPositionPoints}",
    category: "standings",
    categoryKey: "UE_VAR_CAT_STANDINGS",
    type: "Decimal",
    descriptionKey: "UE_VAR_DESC_STANDINGS_POS_POINTS",
    example: "15.0",
  },
  {
    expression: "${driver.heatBonusPoints}",
    category: "standings",
    categoryKey: "UE_VAR_CAT_STANDINGS",
    type: "Decimal",
    descriptionKey: "UE_VAR_DESC_STANDINGS_BONUS_POINTS",
    example: "2.0",
  },
  {
    expression: "${driver.totalPoints}",
    category: "standings",
    categoryKey: "UE_VAR_CAT_STANDINGS",
    type: "Decimal",
    descriptionKey: "UE_VAR_DESC_STANDINGS_TOTAL_POINTS",
    example: "43.0",
  },

  // 2. Heats (items="heats" var="heat")
  {
    expression: "${heat.heatNumber}",
    category: "heats",
    categoryKey: "UE_VAR_CAT_HEATS",
    type: "Number",
    descriptionKey: "UE_VAR_DESC_HEATS_HEAT_NUMBER",
    example: "1",
  },
  {
    expression: "${heat.group}",
    category: "heats",
    categoryKey: "UE_VAR_CAT_HEATS",
    type: "Number",
    descriptionKey: "UE_VAR_DESC_HEATS_GROUP",
    example: "1",
  },
  {
    expression: "${heat.getDriverNameOnLane(0)}",
    category: "heats",
    categoryKey: "UE_VAR_CAT_HEATS",
    type: "String",
    descriptionKey: "UE_VAR_DESC_HEATS_DRIVER_ON_LANE",
    example: '"Austin"',
  },

  // 3. Heat Drivers (items="heat.drivers" var="heatDriver")
  {
    expression: "${heatDriver.actualDriver.name}",
    category: "heatDriver",
    categoryKey: "UE_VAR_CAT_HEAT_DRIVER",
    type: "String",
    descriptionKey: "UE_VAR_DESC_HEAT_DRIVER_ACTUAL_NAME",
    example: '"Austin"',
  },
  {
    expression: "${heatDriver.driver.name}",
    category: "heatDriver",
    categoryKey: "UE_VAR_CAT_HEAT_DRIVER",
    type: "String",
    descriptionKey: "UE_VAR_DESC_HEAT_DRIVER_ENTRY_NAME",
    example: '"Team Red"',
  },
  {
    expression: "${heatDriver.lane}",
    category: "heatDriver",
    categoryKey: "UE_VAR_CAT_HEAT_DRIVER",
    type: "Number",
    descriptionKey: "UE_VAR_DESC_HEAT_DRIVER_LANE",
    example: "1",
  },
  {
    expression: "${heatDriver.adjustedLapCount}",
    category: "heatDriver",
    categoryKey: "UE_VAR_CAT_HEAT_DRIVER",
    type: "Decimal",
    descriptionKey: "UE_VAR_DESC_HEAT_DRIVER_TOTAL_LAPS",
    example: "15.420",
  },
  {
    expression: "${heatDriver.totalTime}",
    category: "heatDriver",
    categoryKey: "UE_VAR_CAT_HEAT_DRIVER",
    type: "Seconds",
    descriptionKey: "UE_VAR_DESC_HEAT_DRIVER_TOTAL_TIME",
    example: "60.050",
  },
  {
    expression: "${heatDriver.bestLapTime}",
    category: "heatDriver",
    categoryKey: "UE_VAR_CAT_HEAT_DRIVER",
    type: "Seconds",
    descriptionKey: "UE_VAR_DESC_HEAT_DRIVER_BEST_LAP",
    example: "3.912",
  },
  {
    expression: "${heatDriver.averageLapTime}",
    category: "heatDriver",
    categoryKey: "UE_VAR_CAT_HEAT_DRIVER",
    type: "Seconds",
    descriptionKey: "UE_VAR_DESC_HEAT_DRIVER_AVG_LAP",
    example: "4.110",
  },
  {
    expression: "${heatDriver.medianLapTime}",
    category: "heatDriver",
    categoryKey: "UE_VAR_CAT_HEAT_DRIVER",
    type: "Seconds",
    descriptionKey: "UE_VAR_DESC_HEAT_DRIVER_MEDIAN_LAP",
    example: "4.095",
  },
  {
    expression: "${heatDriver.gapLeader}",
    category: "heatDriver",
    categoryKey: "UE_VAR_CAT_HEAT_DRIVER",
    type: "String",
    descriptionKey: "UE_VAR_DESC_STANDINGS_GAP_LEADER",
    example: '"+0.850"',
  },
  {
    expression: "${heatDriver.gapPosition}",
    category: "heatDriver",
    categoryKey: "UE_VAR_CAT_HEAT_DRIVER",
    type: "String",
    descriptionKey: "UE_VAR_DESC_STANDINGS_GAP_POSITION",
    example: '"+0.210"',
  },
  {
    expression: "${heatDriver.reactionTime}",
    category: "heatDriver",
    categoryKey: "UE_VAR_CAT_HEAT_DRIVER",
    type: "Seconds",
    descriptionKey: "UE_VAR_DESC_HEAT_DRIVER_REACTION",
    example: "0.150",
  },
  {
    expression: "${heatDriver.falseStarts}",
    category: "heatDriver",
    categoryKey: "UE_VAR_CAT_HEAT_DRIVER",
    type: "Number",
    descriptionKey: "UE_VAR_DESC_HEAT_DRIVER_FALSE_STARTS",
    example: "0",
  },

  // 4. Laps & Telemetry (items="laps" var="lap" and items="heat.lapRows" var="lap")
  {
    expression: "${lap.lapNumber}",
    category: "laps",
    categoryKey: "UE_VAR_CAT_LAPS",
    type: "Number",
    descriptionKey: "UE_VAR_DESC_LAPS_LAP_NUMBER",
    example: "1",
  },
  {
    expression: "${lap.lapTime}",
    category: "laps",
    categoryKey: "UE_VAR_CAT_LAPS",
    type: "Seconds",
    descriptionKey: "UE_VAR_DESC_LAPS_LAP_TIME",
    example: "4.102",
  },
  {
    expression: "${lap.actualDriverName}",
    category: "laps",
    categoryKey: "UE_VAR_CAT_LAPS",
    type: "String",
    descriptionKey: "UE_VAR_DESC_LAPS_DRIVER_NAME",
    example: '"Austin"',
  },
  {
    expression: "${lap.laneNumber}",
    category: "laps",
    categoryKey: "UE_VAR_CAT_LAPS",
    type: "Number",
    descriptionKey: "UE_VAR_DESC_LAPS_LANE",
    example: "2",
  },
  {
    expression: "${lap.heatNumber}",
    category: "laps",
    categoryKey: "UE_VAR_CAT_LAPS",
    type: "Number",
    descriptionKey: "UE_VAR_DESC_HEATS_HEAT_NUMBER",
    example: "1",
  },
  {
    expression: "${lap.absoluteHeatLapTime}",
    category: "laps",
    categoryKey: "UE_VAR_CAT_LAPS",
    type: "Seconds",
    descriptionKey: "UE_VAR_DESC_LAP_VALUES",
    example: "12.450",
  },
  {
    expression: "${val}",
    category: "laps",
    categoryKey: "UE_VAR_CAT_LAPS",
    type: "Seconds",
    descriptionKey: "UE_VAR_DESC_LAP_VAL",
    example: "4.120",
  },
  {
    expression: "${segment}",
    category: "laps",
    categoryKey: "UE_VAR_CAT_LAPS",
    type: "Seconds",
    descriptionKey: "UE_VAR_DESC_LAP_SEGMENT",
    example: "1.420",
  },

  // 5. Driver Summaries (items="driverSummaries" var="ds" / var="ls")
  {
    expression: "${ds.driverName}",
    category: "driverSummaries",
    categoryKey: "UE_VAR_CAT_SUMMARIES",
    type: "String",
    descriptionKey: "UE_VAR_DESC_SUMMARIES_DRIVER_NAME",
    example: '"Austin"',
  },
  {
    expression: "${ls.laneName}",
    category: "driverSummaries",
    categoryKey: "UE_VAR_CAT_SUMMARIES",
    type: "String",
    descriptionKey: "UE_VAR_DESC_HEAT_DRIVER_LANE",
    example: '"Lane 1"',
  },
  {
    expression: "${ls.totalLaps}",
    category: "driverSummaries",
    categoryKey: "UE_VAR_CAT_SUMMARIES",
    type: "Decimal",
    descriptionKey: "UE_VAR_DESC_SUMMARIES_TOTAL_LAPS",
    example: "15.0",
  },
  {
    expression: "${ls.totalTime}",
    category: "driverSummaries",
    categoryKey: "UE_VAR_CAT_SUMMARIES",
    type: "Seconds",
    descriptionKey: "UE_VAR_DESC_SUMMARIES_TOTAL_TIME",
    example: "60.120",
  },
  {
    expression: "${ls.bestLapTime}",
    category: "driverSummaries",
    categoryKey: "UE_VAR_CAT_SUMMARIES",
    type: "Seconds",
    descriptionKey: "UE_VAR_DESC_SUMMARIES_BEST_LAP",
    example: "3.850",
  },
  {
    expression: "${ls.averageLapTime}",
    category: "driverSummaries",
    categoryKey: "UE_VAR_CAT_SUMMARIES",
    type: "Seconds",
    descriptionKey: "UE_VAR_DESC_SUMMARIES_AVG_LAP",
    example: "4.020",
  },
  {
    expression: "${ls.medianLapTime}",
    category: "driverSummaries",
    categoryKey: "UE_VAR_CAT_SUMMARIES",
    type: "Seconds",
    descriptionKey: "UE_VAR_DESC_SUMMARIES_MEDIAN_LAP",
    example: "3.990",
  },
  {
    expression: "${ls.consistencyScore}",
    category: "driverSummaries",
    categoryKey: "UE_VAR_CAT_SUMMARIES",
    type: "Percentage",
    descriptionKey: "UE_VAR_DESC_SUMMARIES_CONSISTENCY",
    example: "97.8%",
  },
  {
    expression: "${ls.standardDeviation}",
    category: "driverSummaries",
    categoryKey: "UE_VAR_CAT_SUMMARIES",
    type: "Decimal",
    descriptionKey: "UE_VAR_DESC_SUMMARIES_STD_DEV",
    example: "0.112",
  },
  {
    expression: "${ls.averageTop5}",
    category: "driverSummaries",
    categoryKey: "UE_VAR_CAT_SUMMARIES",
    type: "Seconds",
    descriptionKey: "UE_VAR_DESC_SUMMARIES_TOP5",
    example: "3.890",
  },

  // 6. Season Standings (items="seasonStandings" var="standing")
  {
    expression: "${seasonName}",
    category: "season",
    categoryKey: "UE_VAR_CAT_SEASON",
    type: "String",
    descriptionKey: "UE_VAR_DESC_SEASON_NAME",
    example: '"Summer Championship"',
  },
  {
    expression: "${standing.rank}",
    category: "season",
    categoryKey: "UE_VAR_CAT_SEASON",
    type: "Number",
    descriptionKey: "UE_VAR_DESC_SEASON_POSITION",
    example: "1",
  },
  {
    expression: "${standing.driverName}",
    category: "season",
    categoryKey: "UE_VAR_CAT_SEASON",
    type: "String",
    descriptionKey: "UE_VAR_DESC_SEASON_DRIVER_NAME",
    example: '"Dave"',
  },
  {
    expression: "${standing.netPoints}",
    category: "season",
    categoryKey: "UE_VAR_CAT_SEASON",
    type: "Decimal",
    descriptionKey: "UE_VAR_DESC_SEASON_NET_POINTS",
    example: "95.0",
  },
  {
    expression: "${standing.grossPoints}",
    category: "season",
    categoryKey: "UE_VAR_CAT_SEASON",
    type: "Decimal",
    descriptionKey: "UE_VAR_DESC_SEASON_GROSS_POINTS",
    example: "110.0",
  },
  {
    expression: "${standing.racesRun}",
    category: "season",
    categoryKey: "UE_VAR_CAT_SEASON",
    type: "Number",
    descriptionKey: "UE_VAR_DESC_SEASON_EVENTS",
    example: "5",
  },

  // 7. Race Metadata (var="race")
  {
    expression: "${race.name}",
    category: "race",
    categoryKey: "UE_VAR_CAT_RACE",
    type: "String",
    descriptionKey: "UE_VAR_DESC_RACE_NAME",
    example: '"Grand Prix Championship"',
  },
  {
    expression: "${race.startTime}",
    category: "race",
    categoryKey: "UE_VAR_CAT_RACE",
    type: "String",
    descriptionKey: "UE_VAR_DESC_RACE_START_TIME",
    example: '"2026-09-11 19:30:00"',
  },
  {
    expression: "${race.track.name}",
    category: "race",
    categoryKey: "UE_VAR_CAT_RACE",
    type: "String",
    descriptionKey: "UE_VAR_DESC_RACE_TRACK_NAME",
    example: '"Daytona Raceway"',
  },
  {
    expression: "${race.track.sections}",
    category: "race",
    categoryKey: "UE_VAR_CAT_RACE",
    type: "Number",
    descriptionKey: "UE_VAR_DESC_RACE_TRACK_SECTIONS",
    example: "3",
  },
  {
    expression: "${race.raceModel.minLapTime}",
    category: "race",
    categoryKey: "UE_VAR_CAT_RACE",
    type: "Seconds",
    descriptionKey: "UE_VAR_DESC_RACE_MIN_LAP",
    example: "2.5",
  },
  {
    expression: "${race.raceModel.heatRotationType}",
    category: "race",
    categoryKey: "UE_VAR_CAT_RACE",
    type: "String",
    descriptionKey: "UE_VAR_DESC_RACE_ROTATION_TYPE",
    example: '"Round Robin"',
  },
  {
    expression: "${race.raceModel.heatScoring.finishMethod}",
    category: "race",
    categoryKey: "UE_VAR_CAT_RACE",
    type: "String",
    descriptionKey: "UE_VAR_DESC_RACE_FINISH_METHOD",
    example: '"Lap Limit"',
  },
  {
    expression: "${race.raceModel.heatScoring.finishValue}",
    category: "race",
    categoryKey: "UE_VAR_CAT_RACE",
    type: "Number",
    descriptionKey: "UE_VAR_DESC_RACE_FINISH_VALUE",
    example: "20",
  },
];
