syntax = "proto3";
package com.antigravity;

option java_package = "com.antigravity.proto";
option java_multiple_files = true;

message SeasonStanding {
  string driver_id = 1;
  string driver_name = 2;
  double net_points = 3;
  double gross_points = 4;
  int32 races_run = 5;
  double current_race_points = 6;
  double current_race_overall_points = 7;
  double current_race_overall_bonus_points = 8;
  double current_race_heat_points = 9;
  double current_race_heat_bonus_points = 10;
  int32 current_race_overall_rank = 11;
  map<string, double> current_race_overall_bonus_breakdown = 12;
  map<string, double> current_race_heat_bonus_breakdown = 13;
  double dropped_points = 14;
}
